name: Test
on:
  push:
    branches: [master]
    tags: [ v* ]
  pull_request:
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        scalaVersion: ["2.13.10", "3.2.1"]
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: coursier/cache-action@v6
      - uses: olafurpg/setup-scala@v12

      - name: Test
        run: sbt "++${{matrix.scalaVersion}} -v test"

      # - name: Debug over SSH (tmate)
      #   # if: ${{ failure() }}
      #   uses: mxschmitt/action-tmate@v3
      #   with:
      #     limit-access-to-actor: true

  publish:
    needs: [build]
    # if this is not a pull request, run only on master or tags pushes.
    # if this is a pull request, run only when 'publish' label is set
    if: (github.event_name != 'pull_request' && (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v'))) || 
      (github.event_name == 'pull_request' &&  contains(github.event.pull_request.labels.*.name, 'publish'))
    strategy:
      matrix:
        os: [ubuntu-20.04]
        scala: [2.13.10]
        java: [adopt@1.8]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: olafurpg/setup-scala@v12
        with:
          java-version: 8
      - name: Cache SBT
        uses: coursier/cache-action@v6
      - uses: olafurpg/setup-gpg@v3
      - name: Publish
        run: sbt version "git status" ci-release "git status"
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
