name: Test

on:
  push:
    branches: [master]
    tags: [ v* ]
  pull_request:
  workflow_dispatch:

env:
  SBT_OPTS: "-Xms1G -Xmx4G" # Default runner has 7G of RAM. https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources

jobs:
  build:
    strategy:
      matrix:
        scalaVersion: ["2.13.13", "3.3.3"]
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: coursier/cache-action@v6

      - name: Test
        env:
          NODE_OPTIONS: "--openssl-legacy-provider"
        run: sbt "++${{matrix.scalaVersion}} -v test"

      # - name: Debug over SSH (tmate)
      #   # if: ${{ failure() }}
      #   uses: mxschmitt/action-tmate@v3
      #   with:
      #     limit-access-to-actor: true

  publish:
    needs: [build]
    # if this is not a pull request, run only on master or tags pushes.
    # if this is a pull request, run only when 'publish' label is set
    if: (github.event_name != 'pull_request' && (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v'))) || 
      (github.event_name == 'pull_request' &&  contains(github.event.pull_request.labels.*.name, 'publish'))
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Cache SBT
        uses: coursier/cache-action@v6
      - name: Publish
        run: sbt version "git status" ci-release "git status"
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
